### ISSUE TITLE
width and height output /2 

### ISSUE THREAD

**Issue by quangduxng** [mdjfs/react-profile#2]
const onDone = (e: any) => {
        const base64 = e.getDataURL();
        console.log('base64', base64.src);
    }
    return (
        <div className='' >
            <ReactProfile src={imageEditor}
                quality={1}
                initCrop={{
                    height: 100,
                    width: 100,
                    x: 0,
                    y: 0,
                    unit: '%'
                }} cropOptions={{
                    disabled: true
                }}
                onDone={(e) => onDone(e)}
            />

        </div>
    )

**Comment by quangduxng** [comment]
All output is converted to 666x1000

**Comment by mdjfs** [comment]
Yes, it's intentional; the user can upload images in very high resolution that may be too heavy for the profile picture of an application. That's why it automatically resizes the image while preserving its aspect ratio by default

![image](https://github.com/mdjfs/react-profile/assets/56895143/8c8434d3-da9e-4461-8632-3daf47447762)

If your application requires higher image resolution, I recommend edit those parameters, particularly width and height. For example, if the desired output image size is 1500x3000 (aspect ratio 1:2) and the width and height limits are both set to 1000, it will resize to 500x1000. However, if you set both limits to 3000, you'll get the image at the desired resolution
